### ISSUE TITLE
Error while running in core.py

### ISSUE THREAD

**Issue by Tarcyrian** [xsligroup/PyTDDFT-SO#1]
Hi,

when I try to run init.py on my cluster (just with the example provided log and rwf file), I get the following error:
`
Traceback (most recent call last):
  File "/home/luca/Ru/Ru7SOCTest/init.py", line 15, in <module>
    calc.start()
  File "/home/luca/Ru/Ru7SOCTest/run.py", line 64, in start
    calculate.boettger()
  File "/home/luca/Ru/Ru7SOCTest/core.py", line 32, in boettger
    for mu in range(1, Vx.shape[0]+1, 1):
AttributeError: 'NoneType' object has no attribute 'shape'
`
Can you maybe help we with this?

**Comment by cliao25** [comment]
Hi,

I see that you are running PyTDDFT-SO on a Ru system, not the example Ca2+ system I provided. Can you post G16 input?

Thank you

**Comment by Tarcyrian** [comment]
Hi, 
thank you for your answer. My input for the Ru system is attached.
Although the same error message appears when I just use the provided ca2+ log and rwf files in the init.py.
[Ru7SOCtest.txt](https://github.com/xsligroup/PyTDDFT-SO/files/10467078/Ru7SOCtest.txt)

**Comment by cliao25** [comment]
Hi,

I was unable to reproduce your bug, with my example input and yours.

Can you please provide the following information:
1. Read/write permissions for your working directory
2. At the termination of PyTDDFT-SO, what .tmp files are present in the directory
3. Any modifications to PyTDDFT-SO modified
4. Gaussian version
5. Operating system
6. Python version

Additionally, I noticed you used an ECP in your calculation. Although PyTDDFT-SO should run with ECPs, the results is not to be trusted. The theory does not take into consideration ECPs.

**Comment by Tarcyrian** [comment]
Hi,
I fixed the issue, there was something wrong with the python version I used. Thanks for the help!
